### ISSUE TITLE
sk kanaly

### ISSUE THREAD

**Issue by lukinojej** [znelkytv/IPTV-CZ-SK#1]
Bolo by dobre pridať Slovenské kanály

**Comment by znelkytv** [comment]
Ok, budu zítra přidávat. Můžete mi, prosím, přiložit nějaké veřejné M3U8 linky? Můžu si najít sám, ale věřím, že máte nějaké, které bych sám nenašel.

**Comment by lukinojej** [comment]
https://sktv-forwarders.7m.pl/get.php?x=SPORT
https://arenasportslovakia.ddns.net/hls/cetv2.m3u8
http://109.74.145.11:1935/tv8/mp4:tv8.stream_360p/playlist.m3u8
https://live.cdn.joj.sk/live/andromeda/joj_sport-1080.m3u8
https://live.cdn.joj.sk/live/andromeda/jojko-1080.m3u8
http://78.130.250.2:8023/play/a02o/index.m3u8

**Comment by znelkytv** [comment]
Děkuji moc, dnes linky určitě přidám do streamu
