### ISSUE TITLE
Pocuvaj ma ty zmrd soplavy skurveny. Najdem si ta a este spolu so mnou aj dalsi.

### ISSUE THREAD

**Issue by nervos67** [znelkytv/IPTV-CZ-SK#10]
-----------------

**Comment by sleduj-tv** [comment]
AKE DVA LINKY?Zmazem...soros86

**Comment by sleduj-tv** [comment]
Pretože všetky linky sú voľne dostupné online. Alebo sú šifrované cez xtream...

**Comment by sleduj-tv** [comment]
A môžeš prísť... Len či ešte zdravý odídeš

**Comment by sleduj-tv** [comment]
Mám rád návštevy
