### ISSUE TITLE
Mas poslednu sancu ty smrad krpaty.

### ISSUE THREAD

**Issue by nervos67** [znelkytv/IPTV-CZ-SK#11]
Ak nezmazes tie linky co tu mas uvedene v 2 odkazoch budes postupeny na policiu kvoli porusovaniu autorskych prav a sireniu chraneneho obsahu.

**Comment by sleduj-tv** [comment]
tak napis v akych?

**Comment by sleduj-tv** [comment]
pojdes si tam sadnut so mnou? velmi rad... kedze tym, ze chces tie linky pre seba porusujes autorske prava a sirenie chraneneho obsahu tak ty. a si v eu, moze to zmazat operator, na polisov sa toto nedava :D

**Comment by sleduj-tv** [comment]
ja na toto nemam cas a ani nikto iny
