### ISSUE TITLE
co se stalo

### ISSUE THREAD

**Issue by Piccaakak** [znelkytv/IPTV-CZ-SK#14]
jak na znelkytv přišla policie nebo co?

**Comment by znelkytv** [comment]
Ne - sleduj-tv psal Z dovodu autorskych prav, trestnych stihani atd. je doplnok docasne pozastaveny, kym nebude znelkytv na slobode. Playlist je "prozatím" stále k dispozici v Releases 1.0 (není ale na poslední verzi)

**Comment by sleduj-tv** [comment]
+ doplnim, toto si tu nemal pisat ze to je tam, lebo uz ta maju znelky. pokuta uz bude na ceste. 400 tisic eur alebo basa to nie je slaby odvar

**Comment by Piccaakak** [comment]
cože

**Comment by sleduj-tv** [comment]
no co ja viem, to ja som ju dostal, povedali, ze ju daju aj jemu, ja som milionar, ale on? neviem ci na to ma..

**Comment by sleduj-tv** [comment]
hrozi mu, ze ho najdu kazdu sekundu, maju jeho ip, meno, adresu (iba mesto). za vsetko toto moze jedno forum

**Comment by Piccaakak** [comment]
Aha chudák znelkytv byl to borec. jemi ho líto

**Comment by sleduj-tv** [comment]
uz ho upozornila nova, mozno to bolo len na jedno upozornenie

**Comment by sleduj-tv** [comment]
ciastocne si za to moze sam, pretoze na tom fore bol registrovany, aktivny a na iptv-org repozitari stale su ludia v issues, ktori ked nieco zistia, uz nie si na slobode.
nebudem zakryvat spravy z fora, tu ich mate
![image](https://github.com/znelkytv/IPTV-CZ-SK/assets/106910269/91edf243-e0db-4631-b443-1a03e6e9e1d6)
![image](https://github.com/znelkytv/IPTV-CZ-SK/assets/106910269/f93daaa5-da2a-444c-b6dd-3406626544c4)
![image](https://github.com/znelkytv/IPTV-CZ-SK/assets/106910269/13bb4ef7-1fe4-4abc-a67d-979daace4fe5)

**Comment by Piccaakak** [comment]
aha.. chudák maty no, hodně štěstí sleduj-tv třeba můžeš vytvořit něco ty 👍👍
a mohl bys tam dát třeba PPV turnaje pak by bylo o to větší zájem

**Comment by sleduj-tv** [comment]
uz som to vytvoril, znelky tam ma pristup a ppv turnaje si asi necham pre seba, pretoze tieto linky su krehke ako sklo, ked spadne na zem, uz nebude pouzitelne :(

**Comment by Piccaakak** [comment]
dobře děkuju
