### ISSUE TITLE
pokračování hádky mezi dvouma dementama/pirátama

### ISSUE THREAD

**Issue by Piccaakak** [znelkytv/IPTV-CZ-SK#16]

**Comment by Piccaakak** [comment]
Fajn maty, pak třeba pošlu na tu vaší proti pirátskou unii tu tvojí IP, operátor dá více info

**Comment by Piccaakak** [comment]
P,S diky za to smazání ukázalo se že seš posranej až za uši :DDDD

**Comment by sleduj-tv** [comment]
Aby si nesiel sediet :) Lebo uz som volal nie len na cpu ale aj na policie cr.

**Comment by Piccaakak** [comment]
+ všechno to mám v Emailuuu když tu řikáš ty kun da

**Comment by Piccaakak** [comment]
Už se bojím bro 🤣🤣🤣

**Comment by sleduj-tv** [comment]
Maj aj ja mam ako si napisal o sportoch aj vsetko

**Comment by Piccaakak** [comment]
poslal jsem link z fóra který byl veřejný. + jsem posílal pár linku na IPTV github protože jsem nevěděl jak vám ty linky mám vypnout. Mám pro to svoje důůvody :( xdd

**Comment by sleduj-tv** [comment]
Nevies ani co je ddos xD. To len naznacuje aky si debil.

**Comment by sleduj-tv** [comment]
Mame asi chutilo lepidielko, vsak?

**Comment by znelkytv** [comment]
už jsem si ho blockl

**Comment by sleduj-tv** [comment]
Ja? Nechaj ho chudaka. Nech sa nepokaka

**Comment by znelkytv** [comment]
ok necháme ho zit
