### ISSUE TITLE
oficialne linky

### ISSUE THREAD

**Issue by bt4ibwem8** [znelkytv/IPTV-CZ-SK#3]
Je mozne nejako generovat platny link, pokial je sucastou URL dynamicky token? Ako priklad uvediem kanal Jednotka, ktory ma link v nasledovnom formate: `https://n17.stv.livebox.sk/stv-tv/XXX/SK-stv1.smil/chunklist_b5251072.m3u8`
pricom `XXX` je dlhy token, ktory sa vzdy meni po obnoveni streamovania

**Comment by znelkytv** [comment]
Hele, tak to sám nevím, ale znám jeden takový link z SKTVF https://sktv-forwarders.7m.pl/get.php?x=STV1
