### ISSUE TITLE
Minimax, Nickelodeon, Tanečné súťaže TV, Infokanál Tizen

### ISSUE THREAD

**Issue by sleduj-tv** [znelkytv/IPTV-CZ-SK#5]
---------------------------------

**Comment by znelkytv** [comment]
Určitě přidám, chtěl bych další, na této IP jsem si také nějaké našel, ale jen by mě zajímalo, na co je Infokanál Tizen (antik info tv)?

**Comment by sleduj-tv** [comment]
Nie, Tango TV Infokanál

**Comment by sleduj-tv** [comment]
ja tam nemám priamo m3u8 linky na to, pretože to je len test, bude to bežať na webstránke

**Comment by sleduj-tv** [comment]
A to majú ale tanečné súťaže samotné tv kanál, to nie je antik ale slovensky zvaz tanecnych sportov
https://szts.sk/video-archiv/live-stream/
To nie je antik web tv infokanal tizen, to je len infokanal tizen, lenze antik si tam zaplatil reklamu od 6 do 22 hodin takze asi tak.

**Comment by znelkytv** [comment]
Ok Opravím
