### ISSUE TITLE
Linky

### ISSUE THREAD

**Issue by sleduj-tv** [znelkytv/IPTV-CZ-SK#6]
-------------------

**Comment by znelkytv** [comment]
díky moc, našel jsem ještě na té ip asi 25 dalších linků, takže to budu nahrazovat, jestli chceš, **tak tu IPTV moji můžeš dělat se mnou**, ale nemusíš

**Comment by sleduj-tv** [comment]
hej mozes ma dat za parcipanta

**Comment by znelkytv** [comment]
ok dám

**Comment by sleduj-tv** [comment]
dikes

**Comment by znelkytv** [comment]
jsi tam
