### ISSUE TITLE
Hlasovanie

### ISSUE THREAD

**Issue by sleduj-tv** [znelkytv/IPTV-CZ-SK#9]
Ak tu bude 5 hlasov pridám nové stanice z môjho sledovani.tv / sledovanie.tv (mám aj CZ aj SK)

**Comment by Piccaakak** [comment]
Ahoj, mám zájem určitě přidávám další hlas

**Comment by infinitywa** [comment]
Ano přidej

**Comment by adam9251442** [comment]
Ano bylo by fajn přidat

**Comment by zipo89825** [comment]
Ahoj bylo by super přidat další, díky.

**Comment by sleduj-tv** [comment]
ešte počkám na jeden hlas

**Comment by znelkytv** [comment]
Tak ho dám já 😄 přidej plssss
